{% set version = "0.8.0" %}


package:
  name: zizmor
  version: {{ version }}

source:
  url: https://github.com/woodruffw/zizmor/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6d05a646e40f27a83023e46ee6b4a4d5290cc385cd5a2d36f273881a28676fbc

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - zizmor --version
    - zizmor --help

about:
  home: https://github.com/woodruffw/zizmor
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary:  A static analysis tool for GitHub Actions 

extra:
  recipe-maintainers:
    - manics
